name: android-perf (private devices)

on:
  schedule:
    - cron: 0 0,4,8,12,16,20 * * *
  pull_request:
    paths:
      - .github/workflows/android-perf-private-device-experiment.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/android-perf-private-device-experiment.yml
  # Note: GitHub has an upper limit of 10 inputs
  workflow_dispatch:
    inputs:
      models:
        description: Models to be benchmarked
        required: false
        type: string
        default: google/gemma-3-1b-it,Qwen/Qwen3-0.6B,HuggingFaceTB/SmolLM2-135M,meta-llama/Llama-3.2-1B,allenai/OLMo-1B-hf
      devices:
        description: Target devices to run benchmark
        required: false
        type: string
        default: samsung_galaxy_s22_private
      benchmark_configs:
        description: The list of configs used the benchmark
        required: false
        type: string
  workflow_call:
    inputs:
      models:
        description: Models to be benchmarked
        required: false
        type: string
        default: google/gemma-3-1b-it,Qwen/Qwen3-0.6B,HuggingFaceTB/SmolLM2-135M,meta-llama/Llama-3.2-1B,allenai/OLMo-1B-hf
      devices:
        description: Target devices to run benchmark
        required: false
        type: string
        default: samsung_galaxy_s22_private
      benchmark_configs:
        description: The list of configs used the benchmark
        required: false
        type: string

concurrency:
  group: android-perf-private-devices-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:
  android:
    uses: ./.github/workflows/android-perf.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      models: ${{ inputs.models || 'google/gemma-3-1b-it,Qwen/Qwen3-0.6B,HuggingFaceTB/SmolLM2-135M,meta-llama/Llama-3.2-1B,allenai/OLMo-1B-hf' }}
      devices: samsung_galaxy_s22_private
      benchmark_configs: ${{ inputs.benchmark_configs }}
