# From https://github.com/pytorch/test-infra/wiki/Using-Nova-Reusable-Build-Workflows
name: Build M1 Wheels

on:
  pull_request:
    paths:
      - build/packaging/**
      - .github/workflows/build-wheels-m1.yml
  push:
    branches:
      - nightly
      - release/*
    tags:
      # NOTE: Binary build pipelines should only get triggered on release candidate builds
      # Release candidate tags look like: v1.11.0-rc1
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
      - ciflow/binaries/*
  workflow_dispatch:

jobs:
  generate-matrix:
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@release/2.5
    with:
      package-type: wheel
      os: macos-arm64
      test-infra-repository: pytorch/test-infra
      test-infra-ref: release/2.5
      with-cuda: disabled
      with-rocm: disabled

  build:
    needs: generate-matrix
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - repository: pytorch/executorch
            pre-script: build/packaging/pre_build_script.sh
            post-script: build/packaging/post_build_script.sh
            smoke-test-script: build/packaging/smoke_test.py
            package-name: executorch
    name: ${{ matrix.repository }}
    uses: pytorch/test-infra/.github/workflows/build_wheels_macos.yml@release/2.5
    with:
      repository: ${{ matrix.repository }}
      ref: ""
      test-infra-repository: pytorch/test-infra
      test-infra-ref: release/2.5
      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
      # ExecuTorch only needs the first layer of submodules; override the
      # "recursive" default to do less work, and to give the buck daemon fewer
      # files to look at.
      submodules: true
      delocate-wheel: false
      env-var-script: build/packaging/env_var_script_m1.sh
      pre-script: ${{ matrix.pre-script }}
      post-script: ${{ matrix.post-script }}
      package-name: ${{ matrix.package-name }}
      runner-type: macos-m1-stable
      smoke-test-script: ${{ matrix.smoke-test-script }}
      trigger-event: ${{ github.event_name }}
